/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.johnkenney.valorantinfoapi.ui;
import com.johnkenney.valorantinfoapi.Main;
import com.johnkenney.valorantinfoapi.Agents.Agent;
import com.johnkenney.valorantinfoapi.ValorantAgentAPI;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author John
 */
public class AgentWindow extends javax.swing.JFrame {
    ValorantAgentAPI api = ValorantAgentAPI.getInstance();
   
    
   
    public AgentWindow() {
        
        //Used for list model 
        DefaultListModel agentModel = new DefaultListModel();
        initComponents();
        listAgent.setFixedCellHeight(50);
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\main\\java\\com\\johnkenney\\valorantinfoapi\\resources\\valorantIcon.png");  
        this.setIconImage(icon);
        
        Image image;
        
        //Addin all agents to DFL then setting model 
        for(int i = 0; i < api.agents.size(); i++)
        {
            agentModel.addElement(api.agents.get(i).getName());
        }
        listAgent.setModel(agentModel);
 
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentDisplay = new javax.swing.JTextArea();
        lblDisplayedAgent = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAgent = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        agentAbilities = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Page");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Agents");

        agentDisplay.setEditable(false);
        agentDisplay.setColumns(20);
        agentDisplay.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        agentDisplay.setForeground(new java.awt.Color(255, 102, 102));
        agentDisplay.setLineWrap(true);
        agentDisplay.setRows(5);
        agentDisplay.setWrapStyleWord(true
        );
        agentDisplay.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(agentDisplay);

        lblDisplayedAgent.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        lblDisplayedAgent.setForeground(new java.awt.Color(255, 102, 102));

        btnBack.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        listAgent.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        listAgent.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        listAgent.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listAgentValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listAgent);

        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        agentAbilities.setEditable(false);
        agentAbilities.setColumns(20);
        agentAbilities.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        agentAbilities.setForeground(new java.awt.Color(255, 102, 102));
        agentAbilities.setLineWrap(true);
        agentAbilities.setRows(5);
        agentAbilities.setWrapStyleWord(true);
        agentAbilities.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jScrollPane3.setViewportView(agentAbilities);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(lblDisplayedAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(btnBack)))
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDisplayedAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addComponent(jScrollPane2)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomeScreen home = new HomeScreen();
        home.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void listAgentValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listAgentValueChanged
        // TODO add your handling code here:
        // Anytime a new agent is selected in the menu
        //Updated code here used to be under button clicked 
        int idx = listAgent.getSelectedIndex();
        lblDisplayedAgent.setText(api.agents.get(idx).getName());
        agentDisplay.setText("Description: " + api.agents.get(idx).getDescription());
        agentAbilities.setText("Abilities:\n" + api.agents.get(idx).abilities[0].displayName + " " + "\n" +
                                                 api.agents.get(idx).abilities[0].description + "\n" + "\n" +
                                                 api.agents.get(idx).abilities[1].displayName + " " + "\n" +
                                                 api.agents.get(idx).abilities[1].description + "\n" + "\n" +
                                                 api.agents.get(idx).abilities[2].displayName + " " + "\n" +
                                                 api.agents.get(idx).abilities[2].description + "\n" + "\n" +
                                                 api.agents.get(idx).abilities[3].displayName + " " + "\n" +
                                                 api.agents.get(idx).abilities[3].description
                                                 
                
        );
        
        //Since agent pictures are URLs must convert into images 
        try {
        URI imageURI = new URI(api.agents.get(idx).getFullPortrait(2));
            URL agentIconURL = imageURI.toURL();
            Image image = (Image) ImageIO.read(agentIconURL).getScaledInstance(600, 600, 600);
            
            
            Icon icon = new ImageIcon(image);
            jLabel2.setIcon(icon);
            
        }catch (URISyntaxException | IOException ex) {
            Logger.getLogger(AgentWindow.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_listAgentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new AgentWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea agentAbilities;
    private javax.swing.JTextArea agentDisplay;
    private javax.swing.JButton btnBack;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDisplayedAgent;
    private javax.swing.JList<String> listAgent;
    // End of variables declaration//GEN-END:variables
}
