/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.johnkenney.valorantinfoapi.ui;

import com.johnkenney.valorantinfoapi.guns.Gun;
import com.johnkenney.valorantinfoapi.guns.ValorantGunAPI;
import java.awt.Image;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.IOException;
import static java.lang.Short.toString;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author John
 */
public class GunWindow extends javax.swing.JFrame{
    /**
     * Creates new form GunWindow
     */
    ValorantGunAPI api = ValorantGunAPI.getInstance();
    DefaultListModel heavy = new DefaultListModel();
    DefaultListModel rifle = new DefaultListModel();
    DefaultListModel SMG = new DefaultListModel();
    DefaultListModel sniper = new DefaultListModel();
    DefaultListModel sidearm = new DefaultListModel();
    DefaultListModel melee = new DefaultListModel();
    DefaultListModel shotgun = new DefaultListModel();
    
    
    public GunWindow() {
        initComponents();
       
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\main\\java\\com\\johnkenney\\valorantinfoapi\\resources\\valorantIcon.png");  
        this.setIconImage(icon);
        listCat.setFixedCellHeight(50);
        
        for(int i = 0; i < api.guns.size(); i++)
        {
            if("EEquippableCategory::Heavy".equals(api.guns.get(i).getCategory()))
            {
                heavy.addElement(api.guns.get(i).getDisplayName());
            }
            else if("EEquippableCategory::Rifle".equals(api.guns.get(i).getCategory()))
            {
                rifle.addElement(api.guns.get(i).getDisplayName());
            }
            else if("EEquippableCategory::SMG".equals(api.guns.get(i).getCategory( )) )
            {
                SMG.addElement(api.guns.get(i).getDisplayName());
            }
            else if("EEquippableCategory::Sidearm".equals(api.guns.get(i).getCategory( )))
            {
                sidearm.addElement(api.guns.get(i).getDisplayName());
            }
            else if("EEquippableCategory::Sniper".equals(api.guns.get(i).getCategory( )))
            {
                sniper.addElement(api.guns.get(i).getDisplayName());
            }
            else if("EEquippableCategory::Shotgun".equals(api.guns.get(i).getCategory( )))
            {
                shotgun.addElement(api.guns.get(i).getDisplayName());
            }
            else
            {
                melee.addElement(api.guns.get(i).getDisplayName());
            }
        }
        
        
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCat = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSelectedCat = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDisplayedGun = new javax.swing.JLabel();
        lblGunImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaWeaponStats = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weapons Page");

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Guns");

        listCat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        listCat.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        listCat.setForeground(new java.awt.Color(255, 102, 102));
        listCat.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Heavy", "Rifle", "Sidearm", "SMG", "Sniper", "Melee", "Shotgun" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCat.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCatValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCat);

        listSelectedCat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        listSelectedCat.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        listSelectedCat.setForeground(new java.awt.Color(102, 102, 255));
        listSelectedCat.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSelectedCat.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSelectedCatValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listSelectedCat);

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Class");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Guns");

        lblDisplayedGun.setFont(new java.awt.Font("Lucida Console", 2, 14)); // NOI18N

        jtaWeaponStats.setColumns(20);
        jtaWeaponStats.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jtaWeaponStats.setForeground(new java.awt.Color(255, 255, 255));
        jtaWeaponStats.setRows(5);
        jtaWeaponStats.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jtaWeaponStats);

        jButton2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisplayedGun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGunImage, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addGap(186, 186, 186))
                            .addComponent(jScrollPane1)))
                    .addComponent(lblDisplayedGun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGunImage, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listCatValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCatValueChanged
        listSelectedCat.setFixedCellHeight(50);
        if(null == listCat.getSelectedValue())
        {
            
            listSelectedCat.setModel(null);
            
        }
        else // TODO add your handling code here:
        switch (listCat.getSelectedValue()) {
            case "Heavy":
                listSelectedCat.setModel(heavy);
                break;
            case "Rifle":
                listSelectedCat.setModel(rifle);
                break;
            case "SMG":
                listSelectedCat.setModel(SMG);
                break;
            case "Sidearm":
                listSelectedCat.setModel(sidearm);
                break;
            case "Sniper":
                listSelectedCat.setModel(sniper);
                break;
            case "Shotgun":
                listSelectedCat.setModel(shotgun);
                break;
            case "Melee":
                listSelectedCat.setModel(melee);
                break;
        }
      
       
    }//GEN-LAST:event_listCatValueChanged

    private void listSelectedCatValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSelectedCatValueChanged
        // TODO add your handling code here:
        lblDisplayedGun.setText(listSelectedCat.getSelectedValue());
        String tmp = listSelectedCat.getSelectedValue();
        int idx = 1;
        for(int i = 0; i < api.guns.size(); i++)
        {
            if(tmp.equals(api.guns.get(i).getDisplayName()))
            {
                idx = i;
                Gun g = api.guns.get(idx);
            }
            
        }
        System.out.println(idx);
        try {
            
            URI imageURI = new URI(api.guns.get(idx).getdisplayIcon());
            URL gunIconURL = imageURI.toURL();
            Image image = (Image) ImageIO.read(gunIconURL);
            Icon icon = new ImageIcon(image);
            lblGunImage.setIcon(icon);
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(GunWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        jtaWeaponStats.setText(api.guns.get(idx).getWeaponStats());
        
    }//GEN-LAST:event_listSelectedCatValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomeScreen home = new HomeScreen();
        this.setVisible(false);
        home.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GunWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GunWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtaWeaponStats;
    private javax.swing.JLabel lblDisplayedGun;
    private javax.swing.JLabel lblGunImage;
    private javax.swing.JList<String> listCat;
    private javax.swing.JList<String> listSelectedCat;
    // End of variables declaration//GEN-END:variables

   
}
